export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // suppressHydrationWarning: browser extensions (WhatRuns, etc.) inject class
  // attributes onto <html> that React didn't render, causing hydration mismatch
  // warnings in dev mode. Safe here — only suppresses on this one element.
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  )
}
